name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        #conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        conda install conda-build -y
    #- name: Install via setup.py
    #  run: |
    #    $CONDA/bin/python3 setup.py bdist_wheel
    - name: Bulid
      run: |
        conda build recipe
    - name: Upload
      env:
        ANACONDA_TOKEN: ${{github.ANACONDA_TOKEN }}
      run: |
        anaconda upload /opt/conda/conda-bld/linux-64/xprec-*.tar.bz2